<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>

  <PropertyGroup Label="ThunderPropagatorPackages">
    <PackageConfiguration>$(PackageIdConfigurationSuffix)$(PackageIdPlatformSuffix)</PackageConfiguration>
    <ThunderPropagatorVersion>1.0.1-beta.205</ThunderPropagatorVersion>
    <ThunderPropagatorPackageId>ThunderPropagator$(PackageConfiguration)</ThunderPropagatorPackageId>
    <ThunderPropagatorFormatSerializersVersion>1.0.1-beta.4</ThunderPropagatorFormatSerializersVersion>
    <ThunderPropagatorFormatSerializersPrefix>ThunderPropagator.FormatSerializers</ThunderPropagatorFormatSerializersPrefix>
  </PropertyGroup>

  <PropertyGroup Label="ThunderPropagatorFormatSerializersPackages">
    <MessagePackId>$(ThunderPropagatorFormatSerializersPrefix).MessagePack$(PackageConfiguration)</MessagePackId>
    <NetJsonId>$(ThunderPropagatorFormatSerializersPrefix).NetJson$(PackageConfiguration)</NetJsonId>
    <ProtobufId>$(ThunderPropagatorFormatSerializersPrefix).Protobuf$(PackageConfiguration)</ProtobufId>
    <ToonId>$(ThunderPropagatorFormatSerializersPrefix).Toon$(PackageConfiguration)</ToonId>
    <XmlId>$(ThunderPropagatorFormatSerializersPrefix).Xml$(PackageConfiguration)</XmlId>
    <YamlId>$(ThunderPropagatorFormatSerializersPrefix).Yaml$(PackageConfiguration)</YamlId>
  </PropertyGroup>

  <ItemGroup Label="ThunderPropagator Packages">
    <PackageVersion Include="$(ThunderPropagatorPackageId)" Version="$(ThunderPropagatorVersion)"/>
  </ItemGroup>

  <ItemGroup Label="Format Serializer Packages">
    <PackageVersion Include="$(MessagePackId)" Version="$(ThunderPropagatorFormatSerializersVersion)"/>
    <PackageVersion Include="$(NetJsonId)" Version="$(ThunderPropagatorFormatSerializersVersion)"/>
    <PackageVersion Include="$(ProtobufId)" Version="$(ThunderPropagatorFormatSerializersVersion)"/>
    <PackageVersion Include="$(ToonId)" Version="$(ThunderPropagatorFormatSerializersVersion)"/>
    <PackageVersion Include="$(XmlId)" Version="$(ThunderPropagatorFormatSerializersVersion)"/>
    <PackageVersion Include="$(YamlId)" Version="$(ThunderPropagatorFormatSerializersVersion)"/>
  </ItemGroup>

  <ItemGroup Label="Testing Packages">
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8"/>
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0"/>
    <PackageVersion Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1"/>
    <PackageVersion Include="NetArchTest.Rules" Version="1.3.2"/>
    <PackageVersion Include="NSubstitute" Version="6.1.0"/>
    <PackageVersion Include="xunit" Version="2.9.3"/>
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
  </ItemGroup>
</Project>
