<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <PropertyGroup Label="ThunderPropagatorPackages">
    <ThunderPropagatorFormatSerializersVersion>1.0.1-beta.16</ThunderPropagatorFormatSerializersVersion>
  </PropertyGroup>
  <ItemGroup Label="ThunderPropagator Packages">
    <PackageVersion Include="$(ThunderPropagatorPackageId)" Version="1.0.1-beta.216" />
  </ItemGroup>
  <ItemGroup Label="Format Serializer Packages">
    <PackageVersion Include="$(MessagePackPackageId)" Version="$(ThunderPropagatorFormatSerializersVersion)" />
    <PackageVersion Include="$(NetJsonPackageId)" Version="$(ThunderPropagatorFormatSerializersVersion)" />
    <PackageVersion Include="$(ProtobufPackageId)" Version="$(ThunderPropagatorFormatSerializersVersion)" />
    <PackageVersion Include="$(ToonPackageId)" Version="$(ThunderPropagatorFormatSerializersVersion)" />
    <PackageVersion Include="$(XmlPackageId)" Version="$(ThunderPropagatorFormatSerializersVersion)" />
    <PackageVersion Include="$(YamlPackageId)" Version="$(ThunderPropagatorFormatSerializersVersion)" />
  </ItemGroup>
  <ItemGroup Label="Testing Packages">
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
  </ItemGroup>
</Project>
