<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFrameworks/>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="xunit"/>
    <PackageReference Include="xunit.runner.visualstudio"/>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="FluentAssertions" VersionOverride="7.2.0" />
    <PackageReference Include="BenchmarkDotNet"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ThunderPropagator.SubscriptionMessageFormatters.MessagePack\ThunderPropagator.SubscriptionMessageFormatters.MessagePack.csproj" />
    <ProjectReference Include="..\..\src\ThunderPropagator.SubscriptionMessageFormatters.NetJson\ThunderPropagator.SubscriptionMessageFormatters.NetJson.csproj" />
    <ProjectReference Include="..\..\src\ThunderPropagator.SubscriptionMessageFormatters.Protobuf\ThunderPropagator.SubscriptionMessageFormatters.Protobuf.csproj" />
    <ProjectReference Include="..\..\src\ThunderPropagator.SubscriptionMessageFormatters.Toon\ThunderPropagator.SubscriptionMessageFormatters.Toon.csproj" />
    <ProjectReference Include="..\..\src\ThunderPropagator.SubscriptionMessageFormatters.Xml\ThunderPropagator.SubscriptionMessageFormatters.Xml.csproj" />
    <ProjectReference Include="..\..\src\ThunderPropagator.SubscriptionMessageFormatters.Yaml\ThunderPropagator.SubscriptionMessageFormatters.Yaml.csproj" />
  </ItemGroup>

</Project>
